// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {log} from '../models';
import {main} from '../models';

export function GetLogs():Promise<Array<log.LogItem>>;

export function GetServices():Promise<Array<main.AppNsService>>;

export function OpenHosts():Promise<void>;

export function RefreshHosts():Promise<void>;

export function StartVPN(arg1:main.VPNConfig):Promise<boolean|string>;

export function StopVPN():Promise<void>;
