// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function OpenHosts() {
  return window['go']['main']['App']['OpenHosts']();
}

export function RefreshHosts() {
  return window['go']['main']['App']['RefreshHosts']();
}

export function StartVPN(arg1) {
  return window['go']['main']['App']['StartVPN'](arg1);
}

export function StopVPN() {
  return window['go']['main']['App']['StopVPN']();
}
